apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bamboo-data
  namespace: atlassian-bamboo
spec:
# storageClassName: nfs
  accessModes:
    - ReadWriteOnce
#   - ReadWriteMany
  resources:
    requests:
      storage: 500Gi