apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: atlassian-bamboo
  name: bamboo-server
  namespace: atlassian-bamboo
spec:
  serviceName: bamboo-server
  replicas: 1
  selector:
    matchLabels:
      app: atlassian-bamboo
  template:
    metadata:
      labels:
        app: atlassian-bamboo
    spec:
      initContainers:
      - name: "init-chown-data"
        image: busybox:latest
        imagePullPolicy: Always
        command: ["/bin/sh","-c"]
        args: ["chown -R  65534:65534 /var/atlassian/application-data/bamboo; chmod -R 777 /var/atlassian/application-data/bamboo"]
        volumeMounts:
        - name: bamboo-data
          mountPath: /var/atlassian/application-data/bamboo
          subPath: ""
      containers:
      - name: bamboo-server
        image: atlassian/bamboo-server
        imagePullPolicy: Always
        env:
        - name: JVM_MINIMUM_MEMORY
          value: 512m
        - name: JVM_MAXIMUM_MEMORY
          value: 1024m
        volumeMounts:
        - name: bamboo-data
          mountPath: /var/atlassian/application-data/bamboo
        - name: bamboo-logs
          mountPath: /opt/atlassian/bamboo/logs
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
        - containerPort: 54663
          name: ssh
          protocol: TCP
       #livenessProbe:
       #  failureThreshold: 3
       #  httpGet:
       #    path: /rest/api/latest/server
       #    port: http
       #    scheme: HTTP
       #  initialDelaySeconds: 120
       #  periodSeconds: 5
       #  successThreshold: 1
       #  timeoutSeconds: 5
       #readinessProbe:
       #  failureThreshold: 3
       #  httpGet:
       #    path: /rest/api/latest/server
       #    port: http
       #    scheme: HTTP
       #  initialDelaySeconds: 120
       #  periodSeconds: 5
       #  successThreshold: 1
       #  timeoutSeconds: 3
      volumes:
      - name: bamboo-logs
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: bamboo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi